trayhttpd:
  mem_limit: 2048M
  cpu_shares: 4
  privileged: true
  volumes:
   - ./www:/var/www/html
  working_dir: /var/www/html
  build: config
  links:
    - redis
  ports:
   - "80:80"
  stdin_open: true
  tty: true
redis:
  mem_limit: 512M
  cpu_shares: 4
  image: redis
  ports:
   - "6379:6379"